#!/usr/bin/env python3
"""
Interactive Streamlit dashboard for the Roblox Plus churned subscriber survey.

Run from this folder with:
    streamlit run streamlit_roblox_plus_dashboard.py

The app expects the analysis-ready CSV generated by analyze_roblox_plus_churned.py:
    outputs/analysis_ready_respondent_level.csv
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st


DEFAULT_DATA_PATH = Path("outputs") / "analysis_ready_respondent_level.csv"
LIKELIHOOD_ORDER = ["Very Unlikely", "Unlikely", "Maybe", "Likely", "Very Likely"]
SENTIMENT_ORDER = ["Love it", "Like it", "Neutral", "Dislike it", "Hate it"]
RETENTION_ORDER = ["Low Intent", "Conditional Intent", "High Intent"]


def normalize_text_series(series: pd.Series, missing_label: str = "Missing") -> pd.Series:
    """Return a clean string series that is safe for grouping and display."""
    return (
        series.astype("string")
        .fillna(missing_label)
        .str.strip()
        .replace({"": missing_label, "<NA>": missing_label, "nan": missing_label})
    )


def safe_numeric(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce")


@st.cache_data(show_spinner=False)
def load_data(data_path: str) -> pd.DataFrame:
    path = Path(data_path)
    if not path.exists():
        raise FileNotFoundError(f"Could not find {path}. Run analyze_roblox_plus_churned.py first.")

    df = pd.read_csv(path)
    for column in ["AGE", "TENURE_NUMERIC", "Q10_SCORE"]:
        if column in df.columns:
            df[column] = safe_numeric(df[column])

    if "AGE" in df.columns:
        df["AGE_GROUP"] = pd.cut(
            df["AGE"],
            bins=[12, 17, 24, 34, 44, 54, 200],
            labels=["13-17", "18-24", "25-34", "35-44", "45-54", "55+"],
            include_lowest=True,
        ).astype("string")
        df["AGE_GROUP"] = normalize_text_series(df["AGE_GROUP"])
    else:
        df["AGE_GROUP"] = "Missing"

    for column in [
        "GENDER_LABEL",
        "Q2_LABEL",
        "Q9_LABEL",
        "Q10_LABEL",
        "RETENTION_GROUP",
        "Q12_LABEL",
    ]:
        if column in df.columns:
            df[column] = normalize_text_series(df[column])

    return df


def filter_by_tenure(df: pd.DataFrame) -> tuple[pd.DataFrame, tuple[float, float] | None]:
    st.sidebar.subheader("Global Filters")
    if "TENURE_NUMERIC" not in df.columns or df["TENURE_NUMERIC"].dropna().empty:
        st.sidebar.info("Tenure is unavailable, so the tenure filter is disabled.")
        return df, None

    tenure = df["TENURE_NUMERIC"].dropna()
    min_tenure = float(tenure.min())
    max_tenure = float(tenure.max())

    if min_tenure == max_tenure:
        st.sidebar.info(f"All respondents have the same tenure: {min_tenure:,.0f}.")
        return df, (min_tenure, max_tenure)

    selected_range = st.sidebar.slider(
        "Account lifetime / tenure",
        min_value=min_tenure,
        max_value=max_tenure,
        value=(min_tenure, max_tenure),
        step=1.0,
        help="Filters every dashboard tab by respondent account lifetime.",
    )

    filtered = df[
        df["TENURE_NUMERIC"].between(selected_range[0], selected_range[1], inclusive="both")
        | df["TENURE_NUMERIC"].isna()
    ].copy()
    return filtered, selected_range


def apply_deep_dive_segment_filter(df: pd.DataFrame) -> pd.DataFrame:
    st.sidebar.subheader("Deep Dive Slices")
    segment_options = {
        "Gender": "GENDER_LABEL",
        "Age Group": "AGE_GROUP",
        "Retention Intent": "RETENTION_GROUP",
        "Future Feature Pick": "Q12_LABEL",
    }
    segment_name = st.sidebar.selectbox("Segment dimension", list(segment_options.keys()))
    segment_column = segment_options[segment_name]

    if segment_column not in df.columns:
        st.sidebar.info(f"{segment_name} is unavailable in the respondent-level file.")
        return df

    values = sorted(normalize_text_series(df[segment_column]).dropna().unique().tolist())
    selected_values = st.sidebar.multiselect(
        f"Filter {segment_name}",
        values,
        default=values,
        help="Applies to the Deep Dive tab only.",
    )
    if not selected_values:
        return df.iloc[0:0].copy()
    return df[df[segment_column].isin(selected_values)].copy()


def percent(numerator: float, denominator: float) -> float:
    if denominator in (0, None) or pd.isna(denominator):
        return 0.0
    return float(numerator) / float(denominator)


def kpi_cards(df: pd.DataFrame) -> None:
    total = len(df)
    high_intent = int(df.get("Q10_SCORE", pd.Series(dtype=float)).isin([4, 5]).sum())
    maybe_or_better = int(df.get("Q10_SCORE", pd.Series(dtype=float)).ge(3).sum())
    median_tenure = df["TENURE_NUMERIC"].median() if "TENURE_NUMERIC" in df.columns else pd.NA

    top_feature = "Unavailable"
    if "Q12_LABEL" in df.columns and not df["Q12_LABEL"].dropna().empty:
        top_feature = normalize_text_series(df["Q12_LABEL"]).value_counts().idxmax()

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Respondents", f"{total:,}")
    col2.metric("High Return Intent", f"{percent(high_intent, total):.1%}")
    col3.metric("Maybe or Better", f"{percent(maybe_or_better, total):.1%}")
    col4.metric("Median Tenure", "N/A" if pd.isna(median_tenure) else f"{median_tenure:,.0f}")

    st.caption(f"Top future feature demand among filtered respondents: **{top_feature}**")


def executive_summary_tab(df: pd.DataFrame) -> None:
    st.markdown(
        """
        ### Business Takeaway
        This view sizes the filtered churned-subscriber audience and shows how much
        recoverable demand remains after cancellation. The funnel is intended to
        separate broad churn volume from users who still show return potential.
        """
    )
    kpi_cards(df)

    total = len(df)
    has_churn_text = int(
        normalize_text_series(df.get("CHURN_TEXT_COMBINED", pd.Series("", index=df.index)), "").str.len().gt(0).sum()
    )
    maybe_or_better = int(df.get("Q10_SCORE", pd.Series(dtype=float)).ge(3).sum())
    high_intent = int(df.get("Q10_SCORE", pd.Series(dtype=float)).isin([4, 5]).sum())

    funnel = pd.DataFrame(
        {
            "stage": [
                "Filtered churned respondents",
                "Provided churn explanation",
                "Maybe / likely to return",
                "Likely / very likely to return",
            ],
            "respondents": [total, has_churn_text, maybe_or_better, high_intent],
        }
    )
    fig = px.funnel(
        funnel,
        x="respondents",
        y="stage",
        title="Recovery Opportunity Funnel",
        color="stage",
    )
    fig.update_layout(showlegend=False, margin=dict(l=20, r=20, t=60, b=20))
    st.plotly_chart(fig, use_container_width=True)


def make_crosstab(df: pd.DataFrame) -> pd.DataFrame:
    if "Q2_LABEL" not in df.columns or "Q10_LABEL" not in df.columns:
        return pd.DataFrame()

    sentiment = pd.Categorical(normalize_text_series(df["Q2_LABEL"]), categories=SENTIMENT_ORDER, ordered=True)
    likelihood = pd.Categorical(normalize_text_series(df["Q10_LABEL"]), categories=LIKELIHOOD_ORDER, ordered=True)
    return pd.crosstab(sentiment, likelihood, dropna=False).reindex(index=SENTIMENT_ORDER, columns=LIKELIHOOD_ORDER, fill_value=0)


def deep_dive_tab(df: pd.DataFrame) -> None:
    st.markdown(
        """
        ### Business Takeaway
        Platform sentiment and likelihood to re-subscribe move together, so this
        slice helps stakeholders identify which audience pockets are still
        persuadable versus structurally resistant.
        """
    )

    if df.empty:
        st.warning("No respondents match the selected segment filters.")
        return

    crosstab = make_crosstab(df)
    if crosstab.empty:
        st.warning("Q2 or Q10 fields are unavailable, so the cross-tab cannot be displayed.")
        return

    row_pct = crosstab.div(crosstab.sum(axis=1).replace(0, pd.NA), axis=0).fillna(0)
    st.subheader("Platform Sentiment by Likelihood to Re-subscribe")
    st.dataframe(
        row_pct.style.format("{:.1%}"),
        use_container_width=True,
    )

    plot_df = row_pct.reset_index(names="Platform Sentiment").melt(
        id_vars="Platform Sentiment",
        var_name="Likelihood to Re-subscribe",
        value_name="Share of Respondents",
    )
    fig = px.bar(
        plot_df,
        x="Platform Sentiment",
        y="Share of Respondents",
        color="Likelihood to Re-subscribe",
        category_orders={
            "Platform Sentiment": SENTIMENT_ORDER,
            "Likelihood to Re-subscribe": LIKELIHOOD_ORDER,
        },
        title="Return Intent Mix by Platform Sentiment",
        text_auto=".0%",
    )
    fig.update_layout(
        barmode="stack",
        yaxis_tickformat=".0%",
        legend_title_text="Likelihood",
        margin=dict(l=20, r=20, t=60, b=20),
    )
    st.plotly_chart(fig, use_container_width=True)


def future_roadmap_tab(df: pd.DataFrame) -> None:
    st.markdown(
        """
        ### Business Takeaway
        Roadmap demand should be read through a growth lens: the toggle below
        removes users already likely to return, highlighting feature concepts that
        may help convert hesitant churned subscribers.
        """
    )

    show_hesitant_only = st.toggle(
        "Show Hesitant Users Only",
        value=False,
        help="When enabled, excludes Likely and Very Likely re-subscribers.",
    )
    working = df.copy()
    if show_hesitant_only and "Q10_SCORE" in working.columns:
        working = working[working["Q10_SCORE"].fillna(0).le(3)].copy()

    if working.empty:
        st.warning("No respondents remain after the roadmap filter.")
        return

    if "Q12_LABEL" not in working.columns:
        st.warning("Q12 future feature selection is unavailable.")
        return

    demand = (
        normalize_text_series(working["Q12_LABEL"])
        .value_counts(dropna=False)
        .rename_axis("Feature")
        .reset_index(name="Respondents")
    )
    demand["Pick Rate"] = demand["Respondents"] / max(len(working), 1)
    demand = demand.sort_values(["Respondents", "Feature"], ascending=[False, True])

    fig = px.bar(
        demand,
        y="Feature",
        x="Pick Rate",
        orientation="h",
        text="Respondents",
        title="Prioritized Future Feature Demand",
        hover_data={"Respondents": True, "Pick Rate": ":.1%"},
    )
    fig.update_layout(
        yaxis={"categoryorder": "total ascending"},
        xaxis_tickformat=".0%",
        margin=dict(l=20, r=20, t=60, b=20),
    )
    st.plotly_chart(fig, use_container_width=True)
    st.dataframe(demand.style.format({"Pick Rate": "{:.1%}"}), use_container_width=True)


def main() -> None:
    st.set_page_config(
        page_title="Roblox Plus Churn Dashboard",
        layout="wide",
    )
    st.title("Roblox Plus Churned Subscriber Dashboard")
    st.caption("Interactive analysis of churn drivers, return intent, and future feature demand.")

    st.sidebar.title("Dashboard Controls")
    data_path = st.sidebar.text_input("Respondent-level CSV", value=str(DEFAULT_DATA_PATH))

    try:
        df = load_data(data_path)
    except Exception as exc:
        st.error(str(exc))
        st.stop()

    tenure_filtered_df, tenure_range = filter_by_tenure(df)
    deep_dive_df = apply_deep_dive_segment_filter(tenure_filtered_df)

    if tenure_range:
        st.sidebar.caption(f"Current tenure range: {tenure_range[0]:,.0f} to {tenure_range[1]:,.0f}")
    st.sidebar.caption(f"Rows after tenure filter: {len(tenure_filtered_df):,}")

    tab1, tab2, tab3 = st.tabs(["Executive Summary", "Deep Dive Slices", "Future Roadmap"])
    with tab1:
        executive_summary_tab(tenure_filtered_df)
    with tab2:
        deep_dive_tab(deep_dive_df)
    with tab3:
        future_roadmap_tab(tenure_filtered_df)


if __name__ == "__main__":
    main()
